services:
  grok2api:
    image: ghcr.io/chenyme/grok2api:latest
    ports:
      - "8000:8000"
    volumes:
      - grok_data:/app/data
      - ./logs:/app/logs
    environment:
      # =====Storage mode: file, mysql or redis=====
      - STORAGE_MODE=file
      # =====Database connection URL (Required only when STORAGE_MODE=mysql or redis)=====
      # - DATABASE_URL=mysql://user:password@host:3306/grok2api

      ## MySQL format: mysql://user:password@host:port/database
      ## Redis format: redis://host:port/db or redis://user:password@host:port/db

volumes:
  grok_data: